import type { Metadata } from "next";
import "./globals.css";
import ClientProvider from "@/components/client-provider/ClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-screen min-h-screen p-10 bg-slate-500">
        <ClientProvider> {children}</ClientProvider>
      </body>
    </html>
  );
}
